<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DailyTracker.Domain\DailyTracker.Domain.csproj" />
    <ProjectReference Include="..\DailyTracker.Application\DailyTracker.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
